openapi: 3.1.0
info:
  title: Neon Notes API
  version: '1.0.0'
servers:
  - url: https://neon-api-3a0h.onrender.com
paths:
  /health:
    get:
      operationId: get_health
      summary: Health check
      responses:
        '200':
          description: OK

  /notes:
    get:
      operationId: get_notes
      summary: List notes
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      operationId: post_notes
      summary: Create a note
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'

  /notes/{id}:
    patch:
      operationId: patch_notes_id
      summary: Update a note
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'

    delete:
      operationId: delete_notes_id
      summary: Delete a note
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API_KEY

  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        tags:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
          description: UTCで保存（ChatGPT表示時にJSTへ変換）
        updated_at:
          type: string
          format: date-time
          nullable: true
          description: UTCで保存（ChatGPT表示時にJSTへ変換）
