openapi: 3.0.0
info:
  title: Neon Notes API
  version: "1.0.0"

servers:
  - url: https://neon-api-3a0h.onrender.com

paths:
  /health:
    get:
      operationId: health
      security: []            # /health は鍵なし
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                required: [ok]

  /notes:
    get:
      operationId: listNotes
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Note"
        "401":
          description: Unauthorized
    post:
      operationId: createNote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required: [content]
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Note"
        "400":
          description: content is required
        "401":
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT   # 固定キーでもOK（表示名として使うだけ）

  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        created_at:
          type: string
          format: date-time
      required: [id, content, created_at]

# 既定で全エンドポイントを「鍵必須」にする（/health は上で上書き）
security:
  - bearerAuth: []

