name: Drive Daily Backup

on:
  schedule:
    # JST 03:00 = UTC 18:00
    - cron: "0 18 * * *"
  workflow_dispatch: {}

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      EXPORT_URL: ${{ secrets.EXPORT_URL }}
      EXPORT_KEY: ${{ secrets.EXPORT_KEY }}
      RCLONE_CONFIG_BLOB: ${{ secrets.RCLONE_CONFIG }}
      DRIVE_DIR: archive/daily

    steps:
      - name: Prepare rclone config
        run: |
          mkdir -p ~/.config/rclone
          printf "%s" "$RCLONE_CONFIG_BLOB" > ~/.config/rclone/rclone.conf
          chmod 600 ~/.config/rclone/rclone.conf

      - name: Install rclone and zip
        run: |
          sudo apt-get update -y
          sudo apt-get install -y rclone zip

      - name: Warm up Render (/health)
        run: |
          curl -fsS https://neon-api-3a0h.onrender.com/health >/dev/null || true
          sleep 5

      - name: Download export.csv (with EXPORT_KEY)
        run: |
          set -euo pipefail
          TODAY=$(date +%Y%m%d)
          curl -fsS -H "Authorization: Bearer ${EXPORT_KEY}" "${EXPORT_URL}" -o "export_${TODAY}.csv"
          test -s "export_${TODAY}.csv"

      - name: Zip the CSV
        run: |
          TODAY=$(date +%Y%m%d)
          zip -q "backup_${TODAY}.zip" "export_${TODAY}.csv"
          zip -T "backup_${TODAY}.zip"

      - name: Upload to Google Drive (rclone)
        run: |
          TODAY=$(date +%Y%m%d)
          rclone copy "backup_${TODAY}.zip" "gdrive:${DRIVE_DIR}/" \
            --transfers=1 --checkers=2 --retries=3 --low-level-retries=5 --stats=10s
