name: Daily CSV Backup

on:
  schedule:
    # 毎日 0:00 UTC（= 日本時間 9:00）
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  actions: read
  contents: write   # 自動コミット用
  issues: write     # 失敗時のIssue起票用

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compute date (UTC)
        id: date
        run: echo "today=$(date -u +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Download /notes/export.csv
        id: dl
        env:
          EXPORT_KEY: ${{ secrets.EXPORT_KEY }}
          RENDER_URL: ${{ vars.RENDER_URL }}
        run: |
          set -e
          mkdir -p backups/tmp

          # 1) CSVをダウンロード（HTTPエラー時失敗: -f, リダイレクト追従: -L, 静かに: -sS）
          curl -fLsS \
            -H "Authorization: Bearer ${EXPORT_KEY}" \
            "${RENDER_URL}/notes/export.csv?limit=10000" \
            -o backups/tmp/export.csv

          # 2) サイズ検証（0バイトは失敗扱い）
          sz=$(wc -c < backups/tmp/export.csv || echo 0)
          echo "size=$sz" >> "$GITHUB_OUTPUT"
          if [ "$sz" -le 0 ]; then
            echo "Downloaded CSV is empty." >&2
            exit 1
          fi

          # 3) 行数（ヘッダー除く）をカウントしてログに出す
          rows=$(tail -n +2 backups/tmp/export.csv | wc -l | tr -d ' ')
          echo "rows=$rows" >> "$GITHUB_OUTPUT"
          echo "Downloaded rows: $rows"

          # 4) 保存ファイル名（UTC日付）
          dest="backups/notes_${{ steps.date.outputs.today }}.csv"
          mkdir -p backups
          mv -f backups/tmp/export.csv "$dest"
          echo "dest=$dest" >> "$GITHUB_OUTPUT"

      - name: Commit CSV to repo
        if: ${{ success() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "${{ steps.dl.outputs.dest }}"
          git commit -m "chore(backup): notes_${{ steps.date.outputs.today }}.csv (rows=${{ steps.dl.outputs.rows }})" || echo "No changes to commit."
          git push

      - name: Open issue if backup failed
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo
            const title = "CSV backup failed"
            const body = [
              "Daily CSV backup failed.",
              `Workflow run: ${context.serverUrl}/${owner}/${repo}/actions/runs/${context.runId}`
            ].join("\n")
            // 既存の未クローズIssueがあれば重複起票しない
            const { data: issues } = await github.rest.issues.listForRepo({
              owner, repo, state: "open", labels: "backup"
            })
            if (!issues.some(i => i.title === title)) {
              await github.rest.issues.create({
                owner, repo, title, body, labels: ["backup"]
              })
            }
