name: purge-soft-deleted

on:
  schedule:
    - cron: '30 18 * * *'   # UTC 18:30 (JST 03:30)
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      RETAIN_DAYS: '30'

    steps:
      - uses: actions/checkout@v4

      - name: Install psql
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Dry run
        id: dry
        shell: bash
        run: |
          COUNT=$(psql "$DATABASE_URL" -Atc "SELECT COUNT(*) FROM notes
            WHERE deleted_at IS NOT NULL
              AND deleted_at < (NOW() - INTERVAL '${RETAIN_DAYS} days')")
          echo "will_delete_count=$COUNT" >> "$GITHUB_OUTPUT"

      - name: Log count
        run: echo "count=${{ steps.dry.outputs.will_delete_count }}"

      - name: Purge
        if: ${{ steps.dry.outputs.will_delete_count != '0' }}
        shell: bash
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -c "DELETE FROM notes
            WHERE deleted_at IS NOT NULL
              AND deleted_at < (NOW() - INTERVAL '${RETAIN_DAYS} days')"
